spring:
  datasource:
    url: jdbc:mysql://13.125.210.17:3306/todo?useSSL=false&serverTimezone=Asia/Seoul
    username: swschool
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
